//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Games.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class comment
    {
        public int Id { get; set; }
       
        public string name { get; set; }
        [Required]
        public string comment1 { get; set; }
        public int gameID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> rating { get; set; }
    
        public virtual game game { get; set; }
    }
}
